name: SDKs Instrumented Tests
description: 'Runs various Kotlin SDK instrumented tests'

inputs:
  name:
    description: 'Name of test and emulator'
    required: true
  command:
    description: 'Gradle task being run'
    required: true
  projectId:
    description: 'WalletConnect projectId'
    required: true
  gmProjectId:
    description: 'GM Dapp projectId'
    required: false
  gmSecret:
    description: 'GM Dapp secret'
    required: false
  testTimeoutSeconds:
    description: 'Seconds for test timeout'
    default: '120'

runs:
  using: "composite"
  steps:
    - name: Create log file
      shell: bash
      run: |
        touch emulator.log
        chmod 777 emulator.log
        adb logcat -s "WalletConnectV2" >> emulator.log &

    - name: Run instrumented tests
      shell: bash
      env:
        WC_CLOUD_PROJECT_ID: ${{ inputs.projectId}}
        TEST_TIMEOUT_SECONDS: ${{ inputs.testTimeoutSeconds }}
        PROD_GM_PROJECT_ID: ${{ inputs.gmProjectId }}
        PROD_GM_SECRET: ${{ inputs.gmSecret }}
      run: ./gradlew ${{ inputs.command }} -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ${{ inputs.name }}
        path: |
          **/reports/**
          emulator.log