name: Android Lint

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  lint:
    name: Run Android Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          architecture: x86_64

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

#      - name: Fetch Properties File
#        env:
#          SECRETS_PROPERTIES: ${{ secrets.SECRETS_PROPERTIES }}
#        run: echo $SECRETS_PROPERTIES | base64 --decode > secrets.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run lint
        run: ./gradlew lint